import Video from '@api.video/nodejs-client/lib/model/Video'
import { PlayerSdk, PlayerTheme } from '@api.video/player-sdk'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import React, { ChangeEvent, useEffect, useState } from 'react'
import useSWR from 'swr'
import { fetcher } from '.'
import {
  Footer,
  GlobalContainer,
  Header,
  InputsContainer,
  PlayerSdkContainer,
  Text,
  TextsContainer,
} from '../style/common'

interface IVideoViewProps {
  children: React.ReactNode
  videoId: string
}
const VideoView: NextPage<IVideoViewProps> = ({ videoId }): JSX.Element => {
  const [player, setPlayer] = useState<PlayerSdk | undefined>(undefined)
  const [playerSettings, setPlayerSettings] = useState<PlayerTheme>({
    link: 'rgb(235, 137, 82)',
    linkHover: 'rgb(240, 95, 12)',
  })
  const [hideControls, setHideControls] = useState<boolean>(false)
  const { data, error } = useSWR<{ video: Video }>(`/api/${videoId}`, fetcher)

  useEffect(() => {
    const player = new PlayerSdk('#player', {
      id: videoId,
    })
    player.setTheme({
      link: 'rgb(235, 137, 82)',
      linkHover: 'rgb(240, 95, 12)',
    })
    setPlayer(player)
  }, [videoId])
  useEffect(() => {
    player && player?.loadConfig({ id: videoId, hideControls: hideControls })
  }, [hideControls, player, videoId])

  const handleChangeSetting = (
    e: ChangeEvent<HTMLInputElement>,
    prop: string
  ) => {
    const newSettings = { ...playerSettings, [prop]: e.currentTarget.value }
    setPlayerSettings(newSettings)
    player?.setTheme(newSettings)
  }

  return (
    <GlobalContainer>
      <Head>
        <title>Video view</title>
        <meta
          name="description"
          content="Generated by create next app & created by api.video"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data?.video && !error && <Header>{data.video.title}</Header>}
      <main>
        <PlayerSdkContainer id="player" />
      </main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <span>and</span>
        <a href="https://api.video" target="_blank" rel="noopener noreferrer">
          api.video
        </a>
      </Footer>
    </GlobalContainer>
  )
}

export default VideoView

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { videoId } = context.query
  return { props: { videoId } }
}
