import Video from '@api.video/nodejs-client/lib/model/Video'
import { PlayerSdk } from '@api.video/player-sdk'
import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect } from 'react'
import useSWR from 'swr'
import { fetcher } from '.'

interface IVideoViewProps {
  children: React.ReactNode
  videoId: string
}
const VideoView: NextPage<IVideoViewProps> = ({ videoId }): JSX.Element => {
  const { data, error } = useSWR<{ video: Video }>(`/api/${videoId}`, fetcher)

  useEffect(() => {
    const player = new PlayerSdk('#player', {
      id: videoId,
    })
    player.setTheme({
      link: 'rgb(235, 137, 82)',
      linkHover: 'rgb(240, 95, 12)',
    })
  }, [videoId])

  return (
    <div className="global-container">
      <Head>
        <title>Video view</title>
        <meta
          name="description"
          content="Generated by create next app & created by api.video"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data?.video && !error && <header>{data.video.title}</header>}
      <main>
        <div id="player" />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <span>and</span>
        <a href="https://api.video" target="_blank" rel="noopener noreferrer">
          api.video
        </a>
      </footer>
    </div>
  )
}

export default VideoView

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { videoId } = context.query
  return { props: { videoId } }
}
