import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { ChangeEvent, useEffect, useRef, useState } from 'react'
import Card from '../components/Card'
import { VideoUploader, VideoUploadResponse } from '@api.video/video-uploader'
import Status from '../components/Status'
import { useRouter } from 'next/router'
import {
  Button,
  Footer,
  GlobalContainer,
  Header,
  Text,
  TextsContainer,
  VideoCard,
  VideosList,
} from '../style/common'
import useSWR from 'swr'
import VideosListResponse from '@api.video/nodejs-client/lib/model/VideosListResponse'

export const fetcher = async (url: string): Promise<any> => {
  return fetch(url).then((res) => res.json())
}

const Home: NextPage = () => {
  const { data, error } = useSWR<{ videos: VideosListResponse }>(
    '/api/videos',
    fetcher
  )

  return (
    <GlobalContainer>
      <Head>
        <title>Video Uploader</title>
        <meta
          name="description"
          content="Generated by create next app & created by api.video"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <span>api.video videos list</span> 📚
      </Header>

      <main>
        <TextsContainer>
          <Text>
            Hey fellow dev! 👋 <br />
            Welcome to this basic example of videos list provided by{' '}
            <a
              href="https://api.video"
              target="_blank"
              rel="noopener noreferrer"
            >
              api.video
            </a>{' '}
            and powered by{' '}
            <a
              href="https://nextjs.org/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Vercel & Next.js
            </a>
            .
          </Text>
          <Text>
            api.video provides APIs and clients to handle all your video needs.
            <br />
            This app is built with the{' '}
            <a
              href="https://github.com/apivideo/api.video-nodejs-client"
              target="_blank"
              rel="noopener noreferrer"
            >
              api.video Node.js client
            </a>
            .
          </Text>
          <Text>
            You can{' '}
            <a
              href="https://github.com/vercel/next.js/tree/canary/examples/with-apivideo-videos"
              target="_blank"
              rel="noopener noreferrer"
            >
              check the source code on GitHub
            </a>
            .
          </Text>
          <Text>
            Please add your api.video API key in your <i>.env</i> file and let
            the power of the API do the rest 🎩
          </Text>
        </TextsContainer>

        {!data && !error && <div>Loading...</div>}
        {error && <div>An error occured trying to fetch your videos</div>}
        {data && data.videos?.data?.length > 0 && (
          <VideosList>
            {data.videos.data.map((video) => (
              <VideoCard href={`/${video.videoId}`} key={video.videoId}>
                <h3>{video.title}</h3>
                <Image
                  src={video.assets?.thumbnail ?? '/vercel.svg'}
                  alt="Video thumbmail"
                  width={150}
                  height={80}
                />
              </VideoCard>
            ))}
          </VideosList>
        )}
      </main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <span>and</span>
        <a href="https://api.video" target="_blank" rel="noopener noreferrer">
          api.video
        </a>
      </Footer>
    </GlobalContainer>
  )
}

export default Home
